# Generated by Django 5.0.14 on 2026-04-07 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_db_type', models.CharField(max_length=20)),
                ('source_table', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_records', to='connections.connectionconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processed_data_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=300)),
                ('source_db_type', models.CharField(max_length=20)),
                ('source_table', models.CharField(max_length=200)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_files', to=settings.AUTH_USER_MODEL)),
                ('processed_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_files', to='storage.processeddatarecord')),
            ],
            options={
                'db_table': 'exported_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
