# Generated by Django 5.0.14 on 2026-04-11

from django.db import migrations, models


def encrypt_existing_passwords(apps, schema_editor):
    """Encrypt any existing plaintext passwords into the new field."""
    from apps.connections.encryption import encrypt

    ConnectionConfig = apps.get_model("connections", "ConnectionConfig")
    for conn in ConnectionConfig.objects.all():
        if conn.password and not conn.encrypted_password:
            conn.encrypted_password = encrypt(conn.password)
            conn.save(update_fields=["encrypted_password"])


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        # Step 1: Add new encrypted column
        migrations.AddField(
            model_name="connectionconfig",
            name="encrypted_password",
            field=models.TextField(default=""),
        ),
        # Step 2: Copy + encrypt existing plaintext passwords
        migrations.RunPython(encrypt_existing_passwords, migrations.RunPython.noop),
        # Step 3: Remove old plaintext column
        migrations.RemoveField(
            model_name="connectionconfig",
            name="password",
        ),
    ]
